4T2F/PADO

PADO/PADO.xcodeproj/project.pbxproj, PADO/PADO/Authentication/AuthenticationViewModel.swift, PADO/PADO/Authentication/EnterAgeView.swift, PADO/PADO/Authentication/EnterCodeView.swift, PADO/PADO/Authentication/EnterNameView.swift, PADO/PADO/Authentication/EnterPhoneNumberView.swift, PADO/PADO/Authentication/MainAuthenticationView.swift, PADO/PADO/Feed/FeedView.swift, PADO/PADO/Feed/Profile.swift, PADO/PADO/Helpers/NavigationViewStyleHelper.swift, PADO/PADO/Items/VerificationView.swift, PADO/PADO/PADOApp.swift, PADO/PADO/Settings/EditProfileView.swift, PADO/PADO/Settings/SettingsView.swift
- 기존 mm/dd/yyyy 였던 생년월일을 yyyy/mm/dd 로 변경
- Profile, Setting View쪽 더미데이터를 viewModel.currentUser 연결처리
- 회원 가입 할 때 기존 Text("")에 overlay로 텍스트필드를 만들어 사용하던걸 overlay 삭제 후 텍스트필드만 사용하도록 변경
- CodeView Ui 변경
- 네비게이션 히든 처리 해도 스와이프 기능 쓸 수 있는 extension 추가
- 프로필 이름 변경 시 변경된 값으로 저장되게끔 하는 함수 추가
=> Merge Develop to Feature/user

PADO/PADO.xcodeproj/project.pbxproj, PADO/PADO/Authentication/AuthenticationViewModel.swift, PADO/PADO/Authentication/EnterAgeView.swift, PADO/PADO/Authentication/EnterCodeView.swift, PADO/PADO/Authentication/EnterNameView.swift, PADO/PADO/Authentication/EnterPhoneNumberView.swift, PADO/PADO/Extensions/Extensions.swift
🌊 Feat: 빈 화면 터치 시 키보드내림, 생년월일 포커스 수정, 인증번호 60초간 코드 입력 못했을 시 코드 재전송 기능 구현
=> 🌊 Feat: 빈 화면 터치 시 키보드내림, 생년월일 포커스 수정,인증번호 60초간 코드 입력 못했을 시 코드 재전송 기능 구현

PADO/PADO.xcodeproj/project.pbxproj, PADO/PADO/GoogleService-Info.plist, PADO/PADO/Items/FeedSurfers.swift, PADO/PADO/iOS/MainView/Feed/FeedCell.swift, PADO/PADO/iOS/MainView/Feed/FeedView.swift, PADO/PADO/iOS/MainView/Report/ReportResultView.swift, PADO/PADO/iOS/MainView/Report/ReportSelectCellView.swift, PADO/PADO/iOS/MainView/Report/ReportSelectView.swift
- 신고하기 선택 뷰, 신고하기 완료 뷰 UI 작성 
- MainFeedView UI 수정
=> 💄 Design: ReportView UI 작업,MainFeedView UI 수정

PADO/PADO.xcodeproj/project.pbxproj, PADO/PADO/Assets.xcassets/ColorSet/blueButtonColor.colorset/Contents.json, PADO/PADO/Assets.xcassets/ColorSet/mainBackgroundColor.colorset/Contents.json, PADO/PADO/iOS/MyFeed/Component/FollowerUserCellView.swift, PADO/PADO/iOS/MyFeed/Component/FollowingCellView.swift, PADO/PADO/iOS/MyFeed/Component/SearchView.swift, PADO/PADO/iOS/MyFeed/Component/UserCellView.swift, PADO/PADO/iOS/MyFeed/View/FollowView.swift, PADO/PADO/iOS/MyFeed/View/FollowerView.swift, PADO/PADO/iOS/MyFeed/View/FollowingView.swift
- FollowingView, FollowerView
- FollowView에서 사용가능한 component들 추가
=> 💄 Design: FollowView 추가

PADO/PADO/PADOApp.swift, PADO/PADO/iOS/MainView/Comment/CommentCell.swift, PADO/PADO/iOS/MainView/Comment/CommentView.swift, PADO/PADO/iOS/MainView/Comment/FaceMojiCell.swift, PADO/PADO/iOS/MainView/Comment/FaceMojiView.swift, PADO/PADO/iOS/MainView/RedesignMainView/Cell/HeartCommentCell.swift, PADO/PADO/iOS/MainView/RedesignMainView/Cell/MainHeaderCell.swift, PADO/PADO/iOS/MainView/RedesignMainView/View/ReMainView.swift, PADO/PADO/iOS/MainView/Report/ReportSelectView.swift, PADO/PADO/iOS/Notification/NotificationView.swift
=> 💄 Design: 댓글창 수정 및 알림 연결

PADO/PADO/PADOApp.swift, PADO/PADO/iOS/Login/Component/BirthView.swift, PADO/PADO/iOS/Login/Component/CodeView.swift, PADO/PADO/iOS/Login/Component/IdView.swift, PADO/PADO/iOS/Login/Component/LoginCodeView.swift, PADO/PADO/iOS/Login/Component/LoginPhoneNumberView.swift, PADO/PADO/iOS/Login/Component/PhoneNumberView.swift, PADO/PADO/iOS/Login/Component/UseIDModalView.swift, PADO/PADO/iOS/Login/View/LoginView.swift, PADO/PADO/iOS/Login/View/SignUpView.swift, PADO/PADO/iOS/Login/View/StartView.swift, PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift, PADO/PADO/iOS/MainView.swift, PADO/PADO/iOS/MainView/RedesignMainView/View/ReMainView.swift, PADO/PADO/iOS/Model/User.swift, PADO/PADO/iOS/MyFeed/ReMyFeed/ProfileCell.swift, PADO/PADO/iOS/MyFeed/ReMyFeed/ReMyFeedView.swift, PADO/PADO/iOS/Setting/View/SettingProfileView.swift, PADO/PADO/iOS/Setting/View/SettingView.swift
#74 
주요 변경 사항
- AuthenticationViewModel EnvironmentObject로 변경
- currentUser 전역변수에서 변경
- 로그아웃 기능 구현 완료
=> 🌊 Feat: 로그아웃 구현

PADO/PADO.xcodeproj/project.pbxproj, PADO/PADO/iOS/Model/User.swift, PADO/PADO/iOS/MyFeed/ReMyFeed/ProfileCell.swift, PADO/PADO/iOS/Setting/View/SettingProfileView.swift, PADO/PADO/iOS/Setting/View/UserUpdateViewModel.swift
#82 
해야될 일
- 값이 하나만 들어가도 3개의 값이 반영되는 부분 추가 설계 필요
-  현재 값을 하나만 넣어도 나머지는 빈 값으로 들어가도록 조건문이 걸려있습니다.
=> 🌊 Feat: Setting에서 정보 변경 기능 설계

PADO/PADO/iOS/MainView/Feed/Model/StoryModel.swift, PADO/PADO/iOS/MainView/Feed/View/FeedView.swift, PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift, PADO/PADO/iOS/Model/Comment.swift, PADO/PADO/iOS/Model/Post.swift
=> 🌊 Feat: 파이어베이스에서 사진 불러오는 기능 구현

PADO/PADO/iOS/Helpers/Items/LoadingCircleView.swift, PADO/PADO/iOS/Helpers/Services/UpdateImageUrl.swift, PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift, PADO/PADO/iOS/MainView/Feed/View/FeedView.swift, PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
=> 🌊 Feat: asyncImage -> KingFisher 변경

PADO/PADO/iOS/ContentView.swift, PADO/PADO/iOS/Surfing/View/SurfingView.swift, PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
[🐞 Fix: 다른 탭 다녀오면 게시글 추가 안되는 오류 수정](https://github.com/4T2F/PADO/commit/7ee7864e3153b68c4f0edd4db599b99ec9e3b76c) 
[🌊 Feat: 게시글 올리는 함수 구현](https://github.com/4T2F/PADO/commit/ac7e22ee7c40df78207e6396d988c521eece059b)
=> Feature/surfing view : 게시글 올리는 구현

PADO/PADO.xcodeproj/project.pbxproj, PADO/PADO/iOS/Helpers/Services/UpdateImageUrl.swift, PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
UpdateImageUrl 함수에서 Switch 구문으로 사용가능하도록 수정
=> 🌊 Feat: UpdateImageUrl 함수에서 Switch 구문으로 사용가능하도록 수정 

PADO/PADO/iOS/ContentView.swift, PADO/PADO/iOS/MainView/Feed/Cell/StoryCell.swift, PADO/PADO/iOS/MainView/Feed/Model/StoryModel.swift, PADO/PADO/iOS/MainView/Feed/View/FeedView.swift, PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift, PADO/PADO/iOS/Model/User.swift, PADO/PADO/iOS/Surfing/View/SurfingView.swift
[🌊 Feat: 파베에 저장된 username 까지 스토리 셀에 불러오는거 까지 완성](https://github.com/4T2F/PADO/commit/d9e476dde676e841c38ae979a6ca72ed60a95416)
[🌊 Feat: 스토리셀 이미지,이름 불러오기 구현](https://github.com/4T2F/PADO/commit/3ffb50229433690dd0d81bc5be86a3cf3dc177c7)
[Merge branch 'develop' into feature/MainView](https://github.com/4T2F/PADO/commit/1c480be2925823df1e54d51306950fb1fdc48d97)
=> Feature/mainView: 포스팅 되어 있는 스토리셀 이미지, 이름 받아오는 기능 구현

PADO/PADO/iOS/Helpers/Services/UpdateImageUrl.swift, PADO/PADO/iOS/Surfing/Component/CameraAccessView.swift, PADO/PADO/iOS/Surfing/Coordinator/CamerCoordinator.swift, PADO/PADO/iOS/Surfing/View/PostView.swift, PADO/PADO/iOS/Surfing/View/SurfingView.swift, PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
#104
- UpdateImageUrl StorageTypeInput 타입에 따라 스토어에 안올리는 로직 추가
- SurfingView에서 UIImage, Image 값 두개 사용하도록 변경
- PostView에서 dismiss 버튼 클릭시 초기화 로직 추가
=> 🌊 Feat: 게시글 포스팅 기능 구현 

PADO/PADO/iOS/Setting/View/ModalAlertView.swift
#105 
- 설정 - 다른설정들 - 캐시지우기 기능 구현
=> 🌊 Feat: 설정 - 캐시지우기 구현

PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift
[🐞 Fix: 로그인 안되는 오류 해결](https://github.com/4T2F/PADO/commit/40843da3657ff7d8790e3eee438499b1d530bd5e) 
[Merge branch 'develop' into feature/MyFeed](https://github.com/4T2F/PADO/commit/7dba4d1904a03bb0132c2c2fd4f0f69ca94640f7)
[🐞 Fix: 계정삭제 로직 돌아가게 수정](https://github.com/4T2F/PADO/commit/62c5139b3446beb23ace16914a96a76c1e60087c)
=> Feature/my feed: 로그인, 계정 삭제 오류 수정

PADO/PADO/iOS/Helpers/Items/SearchBar.swift
- SearchBar 디자인
- 애니메이션 수정
- 슬라이딩해서 들어오는 애니메이션을 구현하고 싶었으나, 잘 적용되지 않아 그나마 자연스러운 애니메이션으로 교체하였음
- 추후 아래와 같은 `asymmetric`를 사용하여 수정할 예정
```swift
.transition(.asymmetric(
insertion: .move(edge: .trailing),
removal: .move(edge: .trailing)
))
```
=> [Add] feature/Search: SearchBar 디자인, 애니메이션 수정

PADO/PADO.xcodeproj/project.pbxproj, PADO/PADO/iOS/MainView/Feed/Cell/HeartCommentCell.swift, PADO/PADO/iOS/MainView/Feed/Cell/StoryCell.swift, PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift, PADO/PADO/iOS/Model/Heart.swift, PADO/PADO/iOS/Model/Post.swift, PADO/PADO/iOS/Model/Story.swift, PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
#136 
- post컬렉션에 하트 서브컬렉션 추가
- 하트수와 댓글수 필드 추가
- 스냅샷으로 값 변경 바라보게 수정
=> 🌊 Feat: 하트, 댓글 연결 완료

PADO/PADO.xcodeproj/project.pbxproj, PADO/PADO/iOS/ContentView.swift, PADO/PADO/iOS/Follow/Component/FollowerOtherUserCellView.swift, PADO/PADO/iOS/Follow/Component/FollowingCellView.swift, PADO/PADO/iOS/Follow/View/FollowMainView.swift, PADO/PADO/iOS/Follow/View/FollowerView.swift, PADO/PADO/iOS/Follow/ViewModel/FollowViewModel.swift, PADO/PADO/iOS/Helpers/Services/UpdateFollowData.swift, PADO/PADO/iOS/MainView/Comment/Cell/CommentCell.swift, PADO/PADO/iOS/MainView/Comment/View/CommentView.swift, PADO/PADO/iOS/MainView/Feed/Cell/HeartCommentCell.swift, PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift, PADO/PADO/iOS/Model/User.swift, PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift, PADO/PADO/iOS/Profile/View/ProfileBadgeModalView.swift, PADO/PADO/iOS/Profile/View/ProfileView.swift
#145 
[🌊 Feat: 다른 사람 프로필 소셜 아이디 연결](https://github.com/4T2F/PADO/commit/7f6680e6dd42a220eba09865b787d911b768a52c)
[🌊 Feat: 타 프로필에서 팔로우 기능 구현](https://github.com/4T2F/PADO/commit/6af4568c0d35eee98a405caa9785f101720cf819) 
[🌊 Feat: 타 프로필에서 팔로워,팔로잉 수 보이게 구현](https://github.com/4T2F/PADO/commit/99c41e239f418f92e72c0ba312a45f7d13830d32) 
[🌊 Feat: 타 프로필에서 팔로워,팔로잉 뷰 볼 수 있게 구현](https://github.com/4T2F/PADO/commit/737ec2fe6242ff4a10691c7eb1f30a5634421ba8) 
[🌊 Feat: 댓글 누르면 프로필로 이동하도록 구현](https://github.com/4T2F/PADO/commit/b44d56a5f5dcecbe505d5c46962cbeed07952c26) 
[🌊 Feat: 팔로잉, 팔로워 버튼 맞게 열리게 구현](https://github.com/4T2F/PADO/commit/946dabd2745814004eacb9fdb08f2851ef0e5b45)
=> [Add] Feature/main view: 프로필 뷰 구현 완료

PADO/PADO.xcodeproj/project.pbxproj, PADO/PADO/iOS/ContentView.swift, PADO/PADO/iOS/Follow/ViewModel/FollowViewModel.swift, PADO/PADO/iOS/Surfing/View/PostCropView.swift, PADO/PADO/iOS/Surfing/View/PostView.swift, PADO/PADO/iOS/Surfing/View/SuferSelectCell.swift, PADO/PADO/iOS/Surfing/View/SuferSelectView.swift, PADO/PADO/iOS/Surfing/View/SurfingView.swift
#146 
작업 내용
- 서퍼 지정 UI 작업
- 포스팅관련 뷰에 followViewModel 연결
- followViewModel 에서 
- sufferID는 selectSufferID
- sufferNickName 은 selectSufferNickName
- 프로필 이미지 URL 은 selectSufferProfileUrl 에 할당되도록 구현
=> [Add] Feature/firebase - 서퍼 지정 뷰 생성

PADO/PADO.xcodeproj/project.pbxproj, PADO/PADO/Assets.xcassets/MainIcon/plusButton.imageset/Contents.json, PADO/PADO/Assets.xcassets/MainIcon/plusButton.imageset/plusButton.svg, PADO/PADO/iOS/Helpers/Items/CircularImageView.swift, PADO/PADO/iOS/Helpers/Items/RectangleImageView.swift, PADO/PADO/iOS/Helpers/Services/UpdateImageUrl.swift, PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift, PADO/PADO/iOS/Model/Corp.swift, PADO/PADO/iOS/Model/User.swift, PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift, PADO/PADO/iOS/Profile/View/ProfileView.swift, PADO/PADO/iOS/Setting/View/SettingBackProfileCropView.swift, PADO/PADO/iOS/Setting/View/SettingProfileModal.swift, PADO/PADO/iOS/Setting/View/SettingProfileView.swift
#167 
- 프로필 이미지 버튼 선택시 모달 구현
- 이미지 값 파이어베이스, 스토어에 저장
- 배경 이미지 값 user 데이터에 할당하도록 구현
- 내 프로필, 다른사람 프로필에서 이미지가 없을 시 검은화면으로 구현
[🐞 Fix: 두번째 저장부터 저장버튼 활성화 안되던 오류 수정](https://github.com/4T2F/PADO/commit/4e5ad94311825c99a27c41335ec324718fc76c68)
[💄 Design: 프로필 이미지 선택 모달 UI 작업](https://github.com/4T2F/PADO/commit/ec24a25f2f522eb3bf11ce9e62d8abbee8dd8019)
[🌊 Feat: 배경화면 선택 Crop 기능 추가](https://github.com/4T2F/PADO/commit/9331c6a2432df8b35557ca468f37087b98677abc)
[🌊 Feat: 배경화면 데이터베이스, 스토리지 업로드 기능 구현](https://github.com/4T2F/PADO/commit/49144481ac94f3c274ddd2e6d92cf551bf549a31)
[🐞 Fix: 배경화면 이미지가 정상적으로 변경되지 않던 문제 해결](https://github.com/4T2F/PADO/commit/855f06f338e1ad17c05ad561d35c9ba6a0562d2c)
[🌊 Feat: 배경화면 변경 기능 완성](https://github.com/4T2F/PADO/commit/f19d76fec8c78646aa266cf02c4c7bd62d2051f6) 
[✨ Add: …
=> [Add] Feature/firebase - 배경화면 선택기능 추가

PADO/PADO/iOS/MainView/Feed/View/ReFeedView.swift, PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift
[177](https://github.com/4T2F/PADO/issues/177)
구현 된 사항
- 처음 팔로우한 사람들 데이터 받아오기
- 오늘 인기 게시글 받아오기
- 맨 마지막 페이지로 내려가면 추가 데이터 받아오기
추가 구현해야할 사항
- 최상단에서 위로 올리면 새로고침
- 한 번 본거는 맨뒤로 보내버리기
=> Feature/main view: 메인 피드 포스트 가져오기 구현

PADO/PADO/iOS/MainView/Comment/Cell/CommentCell.swift, PADO/PADO/iOS/MainView/Comment/View/CommentView.swift, PADO/PADO/iOS/MainView/Comment/ViewModel/CommentViewModel.swift, PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift, PADO/PADO/iOS/Profile/ViewModel/PostitViewModel.swift
+ 다른사람 프로필에서 팔로워 뷰 이동할 때 생기는 오류 해결
=> 🌊 Feat: 댓글들 유저 데이터 중복 제거 후 받아와서 저장하게 구현

PADO/PADO/iOS/PadoRide/Cell/SufferPostCell.swift, PADO/PADO/iOS/Profile/View/DeleteMessageView.swift, PADO/PADO/iOS/Profile/View/MessageBubbleView.swift, PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift, PADO/PADO/iOS/Profile/View/PostitView.swift, PADO/PADO/iOS/Profile/ViewModel/ProfileViewModel.swift, PADO/PADO/iOS/Report/ProfileReprotModalView.swift, PADO/PADO/iOS/Setting/View/SettingBlockUserView.swift, PADO/PADO/iOS/Surfing/View/PhotoTypeModal.swift, PADO/PADO/iOS/Surfing/View/SurfingView.swift
#226 
방명록 글 삭제 모달UI 수정, 파도타기 게시물들 UI 수정, 상대방 프로필 차단 모달 UI 수정, 모달들 인디케이터 적용
>
=> [Design] Feature/Block - 방명록 글 삭제 모달 및 자잘한 UI 수정

PADO/PADO.xcodeproj/project.pbxproj, PADO/PADO/iOS/ContentView.swift, PADO/PADO/iOS/Helpers/Items/PostSelectModalView.swift, PADO/PADO/iOS/Helpers/Services/DeletePost.swift, PADO/PADO/iOS/Helpers/Services/UpdateHeartData.swift, PADO/PADO/iOS/Login/Component/BirthView.swift, PADO/PADO/iOS/MainView/Comment/Cell/CommentCell.swift, PADO/PADO/iOS/MainView/Comment/View/FaceMojiModalView.swift, PADO/PADO/iOS/MainView/Comment/View/SelectCommentView.swift, PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift, PADO/PADO/iOS/MainView/Feed/View/FeedGuideView.swift, PADO/PADO/iOS/MainView/Feed/View/FeedView.swift, PADO/PADO/iOS/MainView/Feed/View/OnePostModalView.swift, PADO/PADO/iOS/PadoRide/View/PadoRideView.swift, PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift, PADO/PADO/iOS/Profile/ProfileGrid/View/SelectPostView.swift, PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift, PADO/PADO/iOS/Profile/View/PostitCell.swift, PADO/PADO/iOS/Profile/ViewModel/ProfileViewModel.swift, PADO/PADO/iOS/Report/ProfileReprotModalView.swift, PADO/PADO/iOS/Report/ReportCommentView.swift, PADO/PADO/iOS/Report/ReportSelectCellView.swift, PADO/PADO/iOS/Report/ReportSelectView.swift, PADO/PADO/iOS/Report/ReportUserView.swift, PADO/PADO/iOS/Search/ViewModel/SearchViewModel.swift, PADO/PADO/iOS/Setting/View/ModalAlertView.swift, PADO/PADO/iOS/Setting/View/SettingInfoView.swift, PADO/PADO/iOS/Surfing/View/PostView.swift, PADO/PADO/iOS/Surfing/View/SurfingView.swift
변경사항
- 로그인 안했을 때 포스팅 데이터 안가져오는 오류 수정
- 검색 안되는 오류 수정
- 선택 셀에서 멍게 누르면 제목,서퍼프로필 안보이게 변경
- 내 게시글 댓글 삭제, 신고 모달
- 게시글, 파도타기 삭제
- 로그아웃하면 데이터 새로고침 되도록 수정
- userNameID 없으면 튕기는 현상 수정
[🐞 Fix: 각종 오류 해결](https://github.com/4T2F/PADO/commit/2d954be54c3c7ed9f2a121623da0015c3682f721) 
[🌊 Feat: 차단 시 서로 보낸 포스트들 삭제 구현](https://github.com/4T2F/PADO/commit/c9c87d92e46ca3cbf071663b6e07b36ff066a4da)
[🌊 Feat: 팔로우 한 사람이 없거나, 게시글이 없을 때 보여줄 화면 구현](https://github.com/4T2F/PADO/commit/7bd7c9308b41539e5bf653d05905cfd0a6f2d54a)
[🌊 Feat: 각종 모달 수정](https://github.com/4T2F/PADO/commit/a6c664fcab96595ec492012ff5552a68934d21a7) 
[💄 Design: 방명록 삭제 터치하는 공간 변경](https://github.com/4T2F/PADO/commit/90cd85cb1dec5b3c01a749fdd54be0f6515d09e3)
[🌊 Feat: 가입할 때 이용약관 동의 추가](https://github.com/4T2F/PADO/commit/886c54026060c91989f1242de096 …
=> Feature/main view : 배포 전 각종 오류 수정

PADO/PADO/iOS/MainView/Feed/Cell/FeedHeaderCell.swift, PADO/PADO/iOS/Profile/View/ProfileView.swift, PADO/PADO/iOS/Setting/View/SettingInfoView.swift, PADO/PADO/iOS/Surfing/View/PostCropView.swift, PADO/PADO/iOS/Surfing/View/SurfingView.swift
#231 
서핑뷰, 파도타기 네비게이션 적용 / 이용약관, 개인정보처리방침 주소 수정
>
=> [Fix] Feature/block - 서핑뷰, 파도타기 네비게이션 적용 / 이용약관, 개인정보처리방침 주소 수정

PADO/PADO.xcodeproj/project.pbxproj, PADO/PADO/iOS/Helpers/Items/CircularImageView.swift, PADO/PADO/iOS/Helpers/Services/DeletePost.swift, PADO/PADO/iOS/Helpers/Services/UpdateCommentData.swift, PADO/PADO/iOS/Login/Component/BirthView.swift, PADO/PADO/iOS/Login/Component/CodeView.swift, PADO/PADO/iOS/Login/Component/UseIDModalView.swift, PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift, PADO/PADO/iOS/MainView/Comment/Cell/CommentCell.swift, PADO/PADO/iOS/MainView/Comment/View/CommentView.swift, PADO/PADO/iOS/MainView/Comment/View/FaceMojiView.swift, PADO/PADO/iOS/MainView/Comment/ViewModel/CommentViewModel.swift, PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift, PADO/PADO/iOS/MainView/Feed/View/FeedView.swift, PADO/PADO/iOS/MainView/Feed/View/OnePostModalView.swift, PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift, PADO/PADO/iOS/PadoRide/View/PadoRideView.swift, PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift, PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift, PADO/PADO/iOS/Profile/View/PostitView.swift, PADO/PADO/iOS/Profile/View/ProfileView.swift, PADO/PADO/iOS/Setting/View/SettingBackProfileCropView.swift, PADO/PADO/iOS/Setting/View/SettingProfileEditView.swift, PADO/PADO/iOS/Setting/View/SettingProfileModal.swift, PADO/PADO/iOS/Setting/View/SettingProfileView.swift, PADO/PADO/iOS/Setting/View/SettingView.swift, PADO/PADO/iOS/Surfing/View/SurfingSearchView.swift, PADO/PADO/iOS/Surfing/View/SurfingSelectView.swift
[🐞 Fix: 각종 오류 수정](https://github.com/4T2F/PADO/commit/02d6dfd216a84b8fd6a63da18ab301b14d641b4b)
=> Develop: 심사 전 각종 버그 수정

PADO/PADO/iOS/ContentView.swift, PADO/PADO/iOS/Login/Component/BirthView.swift, PADO/PADO/iOS/Login/Component/CodeView.swift, PADO/PADO/iOS/Login/Component/UseIDModalView.swift, PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift, PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift, PADO/PADO/iOS/MainView/Feed/View/OnePostModalView.swift, PADO/PADO/iOS/Model/User.swift, PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift, PADO/PADO/iOS/Setting/View/ModalAlertView.swift
[🌊 Feat: 게시글 삭제 시 새로고침](https://github.com/4T2F/PADO/commit/db35e8caefc40ebd10e1b114a8cc950825d9243c)
=> Develop: 심사 전 마지막 버그 수정

PADO/PADO/iOS/MainView/Comment/View/CommentView.swift, PADO/PADO/iOS/MainView/Comment/View/CommentWriteView.swift, PADO/PADO/iOS/Model/User.swift, PADO/PADO/iOS/PadoRide/ViewModel/PadoRideViewModel.swift, PADO/PADO/iOS/Setting/View/SettingOthersView.swift
[🌊 Feat: 파도타기 저장여부 설정 기능 구현](https://github.com/4T2F/PADO/commit/43ef349e8507c0fddf8bc9d3dbf3931ff717b859)
[🌊 Feat: 댓글 작성후 바로 댓글개수 업데이트](https://github.com/4T2F/PADO/commit/711e93912c013dbf013eb96467ee59dbf0595b1a)
[Merge branch 'develop' into feature/Firebase](https://github.com/4T2F/PADO/commit/883789758b335cf7d5966e459e6b2bde719c7f56)
> A/S 센터 파업중
=> [Add] Feature/firebase - 요청 사항 추가 및 수정

PADO/PADO.xcodeproj/project.pbxproj, PADO/PADO/iOS/Helpers/Services/UpdatePhotomojiData.swift, PADO/PADO/iOS/Helpers/Services/UpdatePushNotiData.swift, PADO/PADO/iOS/MainView/Comment/View/DeleteFaceMojiView.swift, PADO/PADO/iOS/Notification/Cell/FacemojiNotificationCell.swift, PADO/PADO/iOS/PadoRide/View/PadoRideEditView.swift, PADO/PADO/iOS/Setting/View/SettingProfileView.swift, PADO/PADO/iOS/Surfing/View/PostView.swift, PADO/PADO/iOS/Surfing/View/SurfingView.swift
- Drag로 나갈때 이미지데이터 초기화
- 네비게이션 문구 통일
- 페이스모지 -> 포토모지로 변경
>
=> 🐞 Fix: 각종 오류 수정

PADO/PADO/iOS/Helpers/Extensions/Color+.swift, PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift, PADO/PADO/iOS/Setting/View/SettingView.swift
=> 🐞 Fix: 프로필 Disappear 오류 수정

PADO/PADO.xcodeproj/project.pbxproj, PADO/PADO/AppDelegate.swift, PADO/PADO/iOS/ContentView.swift, PADO/PADO/iOS/Helpers/Items/LaunchSTA.swift, PADO/PADO/iOS/Helpers/Services/PushNotificationManager.swift, PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift, PADO/PADO/iOS/MainView.swift, PADO/PADO/iOS/MainView/Feed/Cell/FeedCell.swift, PADO/PADO/iOS/MainView/Feed/View/FeedView.swift, PADO/PADO/iOS/MainView/Feed/View/OnePostModalView.swift, PADO/PADO/iOS/MainView/Feed/ViewModel/FeedViewModel.swift, PADO/PADO/iOS/Model/Post.swift, PADO/PADO/iOS/Model/User.swift, PADO/PADO/iOS/Notification/Cell/PostitNotificationCell.swift, PADO/PADO/iOS/PadoRide/ViewModel/PadoRideViewModel.swift, PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift, PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift, PADO/PADO/iOS/Profile/View/ProfileView.swift, PADO/PADO/iOS/Profile/ViewModel/PostitViewModel.swift, PADO/PADO/iOS/Profile/ViewModel/ProfileViewModel.swift, PADO/PADO/iOS/Setting/View/SettingOthersView.swift, PADO/PADO/iOS/Setting/View/SettingView.swift, PADO/PADO/iOS/Surfing/View/PostView.swift, PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
[🌊 Feat: LaunchScreen 타임 대폭 축소](https://github.com/4T2F/PADO/commit/85067fb54d3358a4b6858dfa5d47a18fdee22a4a)
[🌊 Feat: 파도타기 게시글 없으면 멍게 안나오게 수정](https://github.com/4T2F/PADO/commit/c04480f907787c407557ee1b9e30b2588ee5aed7)
[🌊 Feat: 프로필 데이터 받아오는 로직 수정](https://github.com/4T2F/PADO/commit/024ce1f5a54e2ce57bcb8fdc8d8ab4ed4dd8c85e)
[🌊 Feat: 방명록 알림을 누르면 방명록으로 이동하게 수정](https://github.com/4T2F/PADO/commit/dad20cd2f3bff32251f57c3e828688ab68df9faf) 
[🌊 Feat: 하이라이트 공개 여부 설정 추가](https://github.com/4T2F/PADO/commit/642c792ac8eac42eb3ffbc8ef21c142e46f38e1e) 
[🌊 Feat: 버전 1.0.2 변경](https://github.com/4T2F/PADO/commit/10e9e196a3e98e05160c48d91ec59e2d7d7a9f98)
=> Feature/profile: 버전 1.0.2 업데이트 변경사항

PADO/PADO.xcodeproj/project.pbxproj, PADO/PADO/iOS/ContentView.swift, PADO/PADO/iOS/Helpers/Items/NoItemView.swift, PADO/PADO/iOS/PadoRide/Redesign/Cell/FollowerSuggestionCell.swift, PADO/PADO/iOS/PadoRide/Redesign/Cell/SelectPadoRideUserCell.swift, PADO/PADO/iOS/PadoRide/Redesign/View/PadoRideView1.swift, PADO/PADO/iOS/PadoRide/Redesign/View/SelectUserView.swift, PADO/PADO/iOS/PadoRide/View/PadoRideView.swift, PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift, PADO/PADO/iOS/Profile/View/ProfileView.swift, PADO/PADO/iOS/Search/Component/SearchGuide.swift, PADO/PADO/iOS/Search/View/MainSearchView.swift
=> [Design] Feature/onboarding 파도타기 리디자인

PADO/PADO/iOS/Helpers/Items/CustomTabView.swift, PADO/PADO/iOS/Helpers/Services/DeleteImageUrl.swift, PADO/PADO/iOS/Helpers/Services/UpdateImageUrl.swift, PADO/PADO/iOS/Login/ViewModel/AuthenticationViewModel.swift, PADO/PADO/iOS/MainView/Comment/Cell/FaceMojiCell.swift, PADO/PADO/iOS/MainView/Comment/View/FaceMojiView.swift, PADO/PADO/iOS/MainView/Comment/View/SelectEmojiView.swift, PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift, PADO/PADO/iOS/Setting/View/SettingProfileModal.swift, PADO/PADO/iOS/Setting/View/SettingProfileView.swift, PADO/PADO/iOS/Surfing/ViewModel/SurfingViewModel.swift
[🐞 Fix: 프로필, 배경사진 초기화 관련 오류 해결](https://github.com/4T2F/PADO/commit/2f74cb79c1fced6536fded599825a455e37858d1)
[🐞 Fix: 프로필, 배경사진 초기화 관련 오류 해결](https://github.com/4T2F/PADO/commit/91ee75825bba3b3eee9c18279d28fd596958584f)
[🐞 Fix: 다른 사람 프로필에서 그리드 터치시 배경화면 확대되던 오류 해결](https://github.com/4T2F/PADO/commit/6fa9fb5f2226261f7ef5e0ae026af9e5cf9bb450) 
[🐞 Fix: 포토모지 관련 발생한 오류 수정](https://github.com/4T2F/PADO/commit/0232e89f5c2b2cdd9a295453ed94cfbb9e846a13) 
[🐞 Fix: 로그아웃 후 프로필이 탭바에서 안보이던 오류 수정](https://github.com/4T2F/PADO/commit/4ac5f4a94836b6969fe1f69aeeeee00937b6dea8)
[🐞 Fix: 특정 이미지 안올라가던 오류 수정](https://github.com/4T2F/PADO/commit/00b3da17bcf32ffa8b00d008d0f3735785592475)
[🎨 Style: 주석 수정](https://github.com/4T2F/PADO/commit/6c0ad5f581c9b5b83a77a677fd718071cf2d1ee8)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 …
=> [Add] Feature/firebase - 프로필, 포토모지 오류 수정

PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift, PADO/PADO/iOS/Profile/ProfileGrid/View/SelectPostView.swift, PADO/PADO/iOS/Profile/View/DeleteMessageView.swift, PADO/PADO/iOS/Profile/View/MessageBubbleView.swift, PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift, PADO/PADO/iOS/Profile/View/PostitCell.swift, PADO/PADO/iOS/Profile/View/PostitView.swift, PADO/PADO/iOS/Profile/View/ProfileView.swift, PADO/PADO/iOS/Profile/ViewModel/PostitViewModel.swift, PADO/PADO/iOS/Profile/ViewModel/ProfileViewModel.swift, PADO/PADO/iOS/Report/MailView.swift, PADO/PADO/iOS/Report/ProfileReprotModalView.swift, PADO/PADO/iOS/Report/ReportCommentView.swift, PADO/PADO/iOS/Report/ReportResultView.swift, PADO/PADO/iOS/Report/ReportSelectView.swift, PADO/PADO/iOS/Report/ReportUserView.swift
=> 🎨 Style: 코드 컨벤션 적용

PADO/PADO/iOS/ContentView.swift, PADO/PADO/iOS/Profile/ProfileGrid/Cell/SelectPostCell.swift, PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift, PADO/PADO/iOS/Profile/View/Postit/PostitView.swift, PADO/PADO/iOS/Profile/View/ProfileHeaderView.swift, PADO/PADO/iOS/Profile/View/ProfileView.swift, PADO/PADO/iOS/Profile/ViewModel/PostitViewModel.swift, PADO/PADO/iOS/Profile/ViewModel/ProfileViewModel.swift
@State private 변수들을 뷰모델로 옮긴 뒤 Published로 변경했습니다.
기존 ProfileView와 OtherProfileView에서 중복되는 변수들을 뷰모델로 옮겨줌으로써
중복되지 않고 사용할 수 있게 변경했습니다.
수정되어 있지 않던 컨벤션을 수정했습니다.
>
=> [Refactor] : Refactor/profile 프로필 리팩토링

PADO/PADO/iOS/Feed/Cell/FeedCell.swift, PADO/PADO/iOS/Feed/Cell/FeedHeaderCell.swift, PADO/PADO/iOS/Feed/View/FeedView.swift, PADO/PADO/iOS/Main/View/ContentView.swift, PADO/PADO/iOS/Notification/Cell/CommentNotificationCell.swift, PADO/PADO/iOS/Notification/Cell/FacemojiNotificationCell.swift, PADO/PADO/iOS/Notification/Cell/HeartNotificationCell.swift, PADO/PADO/iOS/Notification/Cell/PadoRideNotificationCell.swift, PADO/PADO/iOS/Notification/Cell/ReplyCommentNotificationCell.swift, PADO/PADO/iOS/Notification/Cell/RequestSurfingNotificationCell.swift, PADO/PADO/iOS/Notification/View/NotificationCell.swift, PADO/PADO/iOS/Notification/View/NotificationView.swift, PADO/PADO/iOS/Profile/ProfileGrid/View/SelectPostView.swift, PADO/PADO/iOS/Profile/View/OtherUserPostGridView.swift, PADO/PADO/iOS/Profile/View/OtherUserProfileView.swift, PADO/PADO/iOS/Profile/View/PostGridView.swift, PADO/PADO/iOS/Profile/View/ProfileView.swift
필요없는데 바라보고 있던 FeedViewModel 로직들 다 제거
>
=> 🩹 Refactor: Profile에서 FeedViewModel 분리

PADO/PADO/iOS/Main/View/ContentView.swift, PADO/PADO/iOS/PadoRide/View/DrawingView.swift, PADO/PADO/iOS/PadoRide/View/PadoRideView.swift, PADO/PADO/iOS/PadoRide/View/SendPadoView.swift, PADO/PADO/iOS/PadoRide/ViewModel/PadoRideViewModel.swift
- 뷰에 있던 함수 뷰모델로 이동
- 사용하지 않아도되는 뷰모델 생성 제거
- 뷰에서 사용되던 State 변수 뷰모델 Published로 변경
- 비즈니스로직 뷰모델로 이동
=> Refactor/padoride padorideView리펙토링 진행
